apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge:  100%
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/eficode-academy/quotes-flask-backend:2.0.0
        name: quotes-flask-backend