apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx # deployment resource name, pods running as a part of deployment will share the same name
  labels:
    app:  nginx # deployment resource label
spec:
  selector:
    matchLabels: # selector label the replicaset looks for
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app:  nginx # pods label that much match selector
        version: latest  # arbitrary label we can match on elsewhere
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginx # name of the container running inside a pod, different from pod name
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80 # port the container is listening to
          name:  nginx
      restartPolicy: Always